### ISSUE TITLE
Allow configuring some of the input using both environment variables and `inputs`

### ISSUE THREAD

**Issue by ehmicky** [steprz/netlify-plugin-stepzen#10]
Netlify allows users to [specify `inputs`](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#inputs) directly in `netlify.toml` (and soon in the UI too).
What are your thoughts on allowing input to be specified either in `netlify.toml` or as environment variables?

**Comment by ehmicky** [comment]
Oh, sorry, that's my mistake: I only meant it for non-security sensitive input. Netlify absolutely discourages using `inputs` for confidential inputs since those are checked into GitHub as you mention. 

Some of the environment variables are clearly confidential, such as `STEPZEN_ADMIN_KEY`, but I was not sure whether others weren't, such as `STEPZEN_NAME`. I most of the environment variables are secret, then it might also make sense to just keep it as environment variables only, to avoid fragmenting the DX (by asking users to place some configuration properties in the UI, and some others either in the UI or `netlify.toml`). If you think this might be the case, please feel free to close this issue, and thanks for sharing your concerns.

**Comment by sridhraj** [comment]
Yes, thank you.. There are currently three required variables. (1) The ADMIN API Key (2) The Account name and (3) A name for the project. It makes sense to keep the first two together. And maybe that the third could be in either place. But as you said in this case, it might make sense not to fragment the DX. 
There are also two optional parameters, a folder name and a configuration set to apply to the project. The folder name packages well with the project name. And the configuration set packages well with the API Key. 
So overall, I am inclined, given the small number of parameters to keep them all in one place.
When we get more sophisticated and start exposing availability zones, and rulesets, and data sets, using the `netlify.toml` file to provide those would certainly make more sense. 
So can we perhaps start with the simple "everything is in the environment" experience and then move to a more flexible solution when we start doing more sophisticated things?
Let me know what you think?
