### ISSUE TITLE
Use `process.env` instead of `netlifyConfig.build.environment`

### ISSUE THREAD

**Issue by ehmicky** [steprz/netlify-plugin-stepzen#11]
Environment variables set both in `netlify.toml` and in the UI can be accessed directly using `process.env`, which is the recommended way to access them.
What are your thoughts on using `process.env` in the following line of code?

https://github.com/steprz/netlify-plugin-stepzen/blob/67dfb0bc9e3dcb8d9eec6cfd126e5c55aff49596/src/index.js#L11

**Comment by sridhraj** [comment]
See the comment on #10

**Comment by ehmicky** [comment]
Unfortunately, this is not possible at the moment. From that perspective, `netlifyConfig.build.environment` sounds good, thanks for the additional information :+1:
