### ISSUE TITLE
User error handling

### ISSUE THREAD

**Issue by ehmicky** [steprz/netlify-plugin-stepzen#12]
Any exception is reported to users as a plugin bug, unless a `try`/`catch` block is used in order to call [the following methods](https://docs.netlify.com/configure-builds/build-plugins/create-plugins/#error-reporting) to report those as user errors instead.

In the following API calls, are there known instances of `4**` failures which should be reported as user errors?

https://github.com/steprz/netlify-plugin-stepzen/blob/67dfb0bc9e3dcb8d9eec6cfd126e5c55aff49596/src/index.js#L73-L83

If so, should those use the `utils.build.failPlugin()` method?

**Comment by sridhraj** [comment]
There are a number of errors, and in many cases, these are fairly complicated corner cases. These errors are reported in the `stepzen` development environment and IDE. So maybe reporting those details here may not be helpful. However, perhaps a generic "Could not deploy the endpoint, check the state using by running the stepzen cli" would be the most helpful here?
Will go with your advice.

**Comment by ehmicky** [comment]
Yes, this sounds like a good approach :+1: 

I am not sure whether this applies to Stepzen API but a common error we see with other similar Netlify Build plugins are authentication errors. For example, entering the wrong credentials as environment variables. Another are configuration errors, such as typos in configuration properties. 

Netlify surfaces errors that are due to users or to plugin bugs differently in the UI. This gives a hint to users on how to solve the problem: either checking their configuration and code (for user errors) or contacting the plugin authors (for plugin errors). Surfacing user errors as such (using the providing utility methods) can improve user experience in that respect. Also, it should lower the number of support requests by clearly indicating that the error is on their end (which is often the case).

A common pattern is to rely on the HTTP response code. Namely, using  a `try`/`catch` block and, if there is a `4**` response, report it as a user error. This is a general pattern though, which might not apply to the most common user-caused Stepzen API errors.

Please let me know what you think!

**Comment by sridhraj** [comment]
I'll make the change to report a generic message with a helpful hint. Once the use ramps up, if we see that some specific issues happen more frequently, we can get more pointed in detecting and proactively addressing those. I'll do that and close this issue, and we can reopen new issues if we see some pattern repeating.
