### ISSUE TITLE
`console.log()` debugging statement

### ISSUE THREAD

**Issue by ehmicky** [steprz/netlify-plugin-stepzen#14]
This plugin prints `PreBuild` when it starts.

https://github.com/steprz/netlify-plugin-stepzen/blob/67dfb0bc9e3dcb8d9eec6cfd126e5c55aff49596/src/index.js#L93

The build logs should already print `onPreBuild` in a header just before that statement, so this line can probably be safely removed. What do you think?

**Comment by sridhraj** [comment]
Yes.
