### ISSUE TITLE
Improvements to README for newcomers.

### ISSUE THREAD

**Issue by ddebrunner** [steprz/netlify-plugin-stepzen#15]
**Describe the bug**

I think some items could be improved in the README.md, to make it clearer for folks new to StepZen:

- define what the StepZen endpoint will be given the environment variables
- some more information on configuration sets. Unclear what I would need to do if needed to have my own database password etc.

**Comment by Cerchie** [comment]
Took a look-- one thing that could be added is a link to docs to explain configurationsets here: ```STEPZEN_CONFIGURATION_SETS is a list of StepZen configurationsets to apply to your schema definitions. This is specified as a comma separated string, and defaults to...``` 

https://my.stepzen.com/docs/build-a-graphql-endpoint/general#exploring-the-configuration

**Comment by sridhraj** [comment]
Assigning to @remotesynth for advice.

After that please assign back to @sridhraj for action. Thanks!

**Comment by stepr-hw** [comment]
@sridhraj @remotesynth The README in question is this right?
https://github.com/steprz/netlify-plugin-stepzen#readme

**Comment by sridhraj** [comment]
> @sridhraj @remotesynth The README in question is this right?
> https://github.com/steprz/netlify-plugin-stepzen#readme
> 

Yes.

**Comment by stepr-hw** [comment]
Can you bundle this fix @sridhraj and @remotesynth 

 I just spotted that we have the wrong email alias on the plugin page
 https://app.netlify.com/teams/stepr-hw/plugins?search=stepzen

team@stepzen.com is the internal alias
should be stepzen-team@stepzen.com

![Screen Shot 2021-06-23 at 6 48 08 PM](https://user-images.githubusercontent.com/66567303/123190071-c0fb4980-d453-11eb-84d6-655af3061813.png)

**Comment by remotesynth** [comment]
I made some tweaks. Hopefully this version is clearer. Leaving this open for feedback.

**Comment by stepr-hw** [comment]
@sridhraj next step here??

**Comment by sridhraj** [comment]
The documentation is updated and correct.

**Comment by sridhraj** [comment]
This issue is now closed.
